[build]
publish = "public"
command = """hugo --minify \
                  --source . \
                  --config config.toml \
                  --themesDir themes \
                  --baseURL https://oscarfernandez.netlify.com"""

[context.production.environment]
HUGO_VERSION = "0.68.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"